/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#acd4ff",
        "on-secondary-container": "#bdc0c0",
        "secondary": "#9b9e9f",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "primary": "#98cbff",
        "on-secondary-fixed-variant": "#595c5d",
        "tertiary-fixed-dim": "#c2def0",
        "on-tertiary-fixed-variant": "#486272",
        "on-primary-fixed": "#00426c",
        "tertiary-fixed": "#d0ecff",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "secondary-container": "#393c3d",
        "error-container": "#7f2927",
        "secondary-dim": "#9b9e9f",
        "primary-dim": "#7abeff",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "secondary-fixed": "#e1e3e3",
        "primary-container": "#004a77",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "tertiary-container": "#d0ecff",
        "tertiary-dim": "#c2def0",
        "on-primary": "#00436d",
        "on-error-container": "#ff9993",
        "on-error": "#490106",
        "on-secondary-fixed": "#3c4040",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "on-primary-fixed-variant": "#005f98",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "error-dim": "#bb5551",
        "error": "#ee7d77",
        "primary-fixed": "#cfe5ff",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "inverse-primary": "#00639e",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "surface-tint": "#98cbff",
        "on-tertiary-container": "#3e5868",
        "primary-fixed-dim": "#b4d8ff",
        "tertiary": "#eff8ff",
        "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "on-tertiary-fixed": "#2c4655",
        "secondary-fixed-dim": "#d2d5d5",
        "on-secondary": "#1d2121",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-tertiary": "#466170",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
