spring.application.name=jinbu

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/jinbu
spring.jpa.database=postgresql
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Max image size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# AWS congig

cloud.aws.region.static=us-east-1

aws.bucket.name=jinbu-s3-bucket

aws.s3.url-base=https://jinbu-s3-bucket.s3.us-east-1.amazonaws.com/
